kind: pipeline
type: docker
name: default

trigger:
  branch: [master]

clone:
  retries: 3
  depth: 1

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gradle-cache
    host:
      path: /srv/gradle/caches
  - name: application-config
    host:
      path: /srv/kenko-drive/config

services:
  - name: redis
    image: redis:7-alpine

steps:
  - name: test and create cache
    image: gradle:jdk17-alpine
    failure: ignore
    volumes:
      - name: gradle-cache
        path: /home/gradle/.gradle
    commands:
      - gradle test -i

  - name: build jar package
    image: gradle:jdk17-alpine
    volumes:
      - name: gradle-cache
        path: /home/gradle/.gradle
    commands:
      - gradle bootJar

  - name: build and deploy container
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: application-config
        path: /drone/src/config
    commands:
      - docker compose -p kenko-drive up -d --build application
