version: '3.1'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "16677:6677"
    volumes:
      - /srv/kenko-drive/data:/app/data
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
