name: kenko-drive

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: service:redis
    volumes:
      - /srv/kenko-drive/data:/app/data
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6677:6677"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drive
      MYSQL_USER: drive
      MYSQL_PASSWORD: drive
    network_mode: service:redis
    volumes:
      - /srv/kenko-drive/mysql/data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1" ]
      interval: 10s

  minio:
    image: minio/minio
    network_mode: service:redis
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    volumes:
      - /srv/kenko-drive/minio/data:/data
    restart: always
    command:
      - server
      - /data

volumes:
  redis-data:
