spring:
  jpa:
    # 开启 SQL 日志
    show-sql: false
    properties:
      hibernate:
        # 格式化 SQL 日志
        format_sql: true
logging:
  # 日志级别
  level:
    # 默认日志级别
    root: warn
    com.akagiyui: trace
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
