server:
  # 等待请求结束后再关闭
  shutdown: graceful
spring:
  lifecycle:
    # 等待请求结束超时时长
    timeout-per-shutdown-phase: 30s
  # !!!在生产环境中，你至少需要正确配置以下内容，使系统能够正常运行!!!
  datasource:
    url: jdbc:mysql://localhost:3306/drive
  data:
    redis:
      host: redis
