# 该文件为基础配置，请不要修改该文件
server:
  # 端口号
  port: 6677
spring:
  application:
    # 服务名称
    name: kenko-drive
  profiles:
    # 激活 生产环境 配置
    active: prod
  jpa:
    hibernate:
      # 自动修正数据表
      ddl-auto: update
  mvc:
    # 抛出 404 异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭静态资源映射
      add-mappings: false
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 线程最长持续时间
      max-lifetime: 30000
      # 最小空闲线程
      minimum-idle: 3
      # 最大线程数
      maximum-pool-size: 10
      # 连接性测试查询
      connection-test-query: SELECT 1
  servlet:
    # 请求大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mail:
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
application:
  # 应用版本号，自动从 build.gradle 中获取
  version: ${version?:unknown}
  email:
    verify:
      # 邮箱验证码超时（分钟）
      timeout: 10
    from: "Kenko Drive"
  jwt:
    # JWT 超时（小时）
    timeout: 2
  storage:
    local:
      # 本地存储路径
      root: ./data
