# 该文件为基础配置，请不要修改该文件
server:
  # 端口号
  port: 6677
  http2:
    # 启用 HTTP2
    enabled: true
spring:
  application:
    # 服务名称
    name: kenko-drive
  profiles:
    # 激活 生产环境 配置
    active: prod
  threads:
    virtual:
      # 开启虚拟线程支持
      enabled: true
  jpa:
    hibernate:
      # 自动修正数据表
      ddl-auto: update
    # 为每一个Http请求分配一个数据库连接
    open-in-view: false
  web:
    resources:
      # 关闭静态资源映射
      add-mappings: false
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 请求大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mail:
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  messages:
    basename: i18n/messages
sentry:
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
application:
  # 应用版本号，自动从 build.gradle 中获取
  version: ${version?:unknown}
  email:
    verify:
      # 邮箱验证码超时（分钟）
      timeout: 10
    from: "Kenko Drive"
  jwt:
    # JWT 超时（小时）
    timeout: 2
  storage:
    local:
      # 本地存储路径
      root: ./data
  avatar:
    default: static/default-avatar.jpg
logging:
  include-application-name: false
