spring:
  jpa:
    # 开启 SQL 日志
    show-sql: true
    properties:
      hibernate:
        # 格式化 SQL 日志
        format_sql: true
  config:
    # 导入 .env.yml 配置，该配置文件优先级最高
    import: optional:classpath:.env.yaml
logging:
  # 日志级别
  level:
    # 默认日志级别
    root: info
    com.akagiyui: trace
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
