spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test?user=test&password=test&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
  data:
    redis:
      host: redis
application:
  storage:
    local:
      root: ./data
