server:
  # 等待请求结束后再关闭
  shutdown: graceful
spring:
  lifecycle:
    # 等待请求结束超时时长
    timeout-per-shutdown-phase: 30s
  config:
    # 导入生产环境配置
    import: optional:file:.env-prod.yaml
  # !!!在生产环境中，你至少需要正确配置以下内容，使系统能够正常运行!!!
  datasource:
    # 数据库驱动
    url: DATABASE_URL
  data:
    redis:
      # redis 地址
      host: REDIS_HOST
  mail:
    # 邮件服务器地址
    host: MAIL_SERVER
    # 邮箱
    username: MAIL_USERNAME
    # 密码
    password: MAIL_PASSWORD
application:
  storage:
    local:
      # 本地文件存储目录
      root: STORAGE_PATH
  email:
    # 邮件发送者名称
    from: MAIL_SENDER_NAME
  jwt:
    # JWT 密钥
    key: YOUR_JWT_KEY
