server:
  # 等待请求结束后再关闭
  shutdown: graceful
spring:
  config:
    # 导入 .env 配置，该配置文件优先级最高
    import:
      - optional:classpath:.env.yaml
      - optional:classpath:.env.yml
      - optional:file:.env.yaml
      - optional:file:.env.yml
  lifecycle:
    # 等待请求结束超时时长
    timeout-per-shutdown-phase: 30s
  # !!!在生产环境中，你至少需要正确配置以下内容，使系统能够正常运行!!!
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost/drive?user=drive&password=drive&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
  data:
    redis:
      # redis 地址
      host: localhost
application:
  storage:
    local:
      # 本地文件存储目录
      root: ./data
      # 上传缓存目录
      cacheRoot: ./data/cache
    minio:
      enable: true
      # MinIO 服务地址
      endpoint: http://localhost:9000
      # MinIO 服务访问密钥
      accessKey: admin
      # MinIO 服务访问密钥
      secretKey: password
      # MinIO 桶名称
      bucket: drive
  token:
    # Token 密钥
    key: YOUR_JWT_KEY
