spring:
  config:
    # 导入 .env 配置，该配置文件优先级最高
    import:
      - optional:classpath:.env.yaml
      - optional:classpath:.env.yml
      - optional:file:.env.yaml
      - optional:file:.env.yml
  jpa:
    # 开启 SQL 日志
    show-sql: false
    properties:
      hibernate:
        # 格式化 SQL 日志
        format_sql: true
logging:
  # 日志级别
  level:
    # 默认日志级别
    root: warn
    com.akagiyui: trace
application:
  storage:
    minio:
      enable: true
