# 该文件为基础配置，请不要修改该文件
server:
  # 端口号
  port: 6677
spring:
  application:
    # 服务名称
    name: kenko-drive-application
  profiles:
    # 激活 生产环境 配置
    active: prod
  threads:
    virtual:
      # 开启虚拟线程支持
      enabled: true
  jpa:
    hibernate:
      # 自动修正数据表，此处待定，可能会导致数据丢失
      ddl-auto: update
    # 为每一个Http请求分配一个数据库连接
    open-in-view: false
  web:
    resources:
      # 静态资源映射
      add-mappings: false
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 请求大小限制
    multipart:
      max-file-size: 1TB
      max-request-size: 1TB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mail:
    # 该配置项仅用于使 IDEA 不报错，实际配置在 application-prod.yaml 中
    # https://youtrack.jetbrains.com/issue/IDEA-262744/Could-not-autowire.-No-beans-of-JavaMailSender-type-found.#focus=Comments-27-5165177.0-0
    host: ~
  messages:
    basename: i18n/messages
  data:
    redis:
      repositories:
        # 启用 Redis Repository 扫描
        enabled: false
logging:
  # 日志包含应用名称
  include-application-name: false
  # 日志级别
  level:
    root: info
sentry:
  # 监控并捕获100%的异常
  traces-sample-rate: 1.0
# 完整的业务相关配置
application:
  name: Kenko Drive
  # 应用版本号，构建时从 build.gradle 中替换
  version: ${version?:unknown}
  # Token 相关配置
  token:
    # 用户 Access Token 超时（小时）
    timeout: 48
    # Token 密钥
    key: THIS_IS_A_SECRET_KEY
  # 存储相关配置
  storage:
    # 本地存储
    local:
      # 本地数据存储目录
      root: ./data
      # 上传缓存目录
      cacheRoot: ./data/cache
    # minio 存储
    minio:
      enable: true
      # MinIO 服务地址
      endpoint: http://localhost:9000
      # MinIO 服务访问密钥
      accessKey: admin
      # MinIO 服务访问密钥
      secretKey: password
      # MinIO 存储桶名称
      bucket: drive
  avatar:
    # 默认头像
    default: static/default-avatar.jpg
