name: Spring Boot Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 在 GitHub Actions 时使用官方源
      # 将 Redis 的 host 替换为 127.0.0.1
      - name: Replace Some Configurations
        run: |
          sed -i 's#mirrors.cloud.tencent.com/gradle#services.gradle.org/distributions#g' gradle/wrapper/gradle-wrapper.properties
          sed -i 's#maven.aliyun.com/repository/gradle-plugin#plugins.gradle.org/m2#g' settings.gradle.kts
          sed -i 's#maven.aliyun.com/repository/public#repo1.maven.org/maven2#g' build.gradle.kts
          sed -i 's#host: redis#host: 127.0.0.1#' src/main/resources/application-test.yaml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon --warning-mode all --scan

      - name: Test with Gradle
        run: ./gradlew test --no-daemon --warning-mode all --scan

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports
            build/test-results

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AkagiYui/KenkoDrive
